name: Deploy Quartz Site to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger the workflow on the master branch

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Quartz code from quartz branch
        uses: actions/checkout@v3
        with:
          ref: quartz
          fetch-depth: 0 # Fetch all history for git info

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.14

      - name: Get main branch name
        id: branch_name
        run: |
          MAIN_BRANCH=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')
          echo "::set-env name=MAIN_BRANCH::$MAIN_BRANCH"

      - name: Move files if needed
        run: |
          git checkout $MAIN_BRANCH -- docs
          mv docs/ content/
          git commit -m "añadidos apuntes automáticamente de master"

      - name: Install Dependencies
        run: npm ci

      - name: Build Quartz
        run: npx quartz build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: public

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
